const dataIcon = [
    {name: 'remixicon-briefcase-5-line', value: 'remixicon-briefcase-5-line'},
    {name: 'remixicon-dashboard-line', value: 'remixicon-dashboard-line'},
    {name: 'remixicon-camera-2-fill', value: 'remixicon-camera-2-fill'},
    {name: 'remixicon-crop-line', value: 'remixicon-crop-line'},
    {name: 'remixicon-customer-service-2-fill', value: 'remixicon-customer-service-2-fill'},
    {name: 'fab fa-telegram-plane', value: 'fab fa-telegram-plane'},
    {name: 'fab fa-gratipay', value: 'fab fa-gratipay'},
    {name: 'fab fa-gg', value: 'fab fa-gg'},
    {name: 'fab fa-elementor', value: 'fab fa-elementor'},
    {name: 'fas fa-atlas', value: 'fas fa-atlas'},
    {name: 'fas fa-chart-bar', value: 'fas fa-chart-bar'},
    {name: 'fas fa-cogs', value: 'fas fa-cogs'},
    {name: 'fas fa-cog', value: 'fas fa-cog'},
    {name: 'fas fa-home', value: 'fas fa-home'},
    {name: 'fas fa-th-large', value: 'fas fa-th-large'},
    {name: 'fas fa-user-cog', value: 'fas fa-user-cog'},
    {name: 'fas fa-users', value: 'fas fa-users'},
    {name: 'fas fa-user-tie', value: 'fas fa-user-tie'},
    {name: 'fas fa-poll-h', value: 'fas fa-poll-h'},
    {name: 'fas fa-file-contract', value: 'fas fa-file-contract'},
    {name: 'fas fa-mail-bulk', value: 'fas fa-mail-bulk'},
    {name: 'fas fa-tasks', value: 'fas fa-tasks'},
    {name: 'fas fa-tools', value: 'fas fa-tools'},
    {name: 'fas fa-trash', value: 'fas fa-trash'},
    {name: 'far fa-address-card', value: 'far fa-address-card'},
    {name: 'far fa-calendar-alt', value: 'far fa-calendar-alt'},
    {name: 'far fa-envelope', value: 'far fa-envelope'},
    {name: 'far fa-edit', value: 'far fa-edit'},
    {name: 'far fa-comments', value: 'far fa-comments'},
    {name: 'far fa-sticky-note', value: 'far fa-sticky-note'},
    {name: 'fab fa-buysellads', value: 'fab fa-buysellads'},
    {name: 'fab fa-qq', value: 'fab fa-qq'},
];
export {dataIcon}
